image: continuumio/anaconda3:latest

stages:
  - build
  # - network_construction

build:
  stage: build
  before_script:
    - conda create -n emergent python=3.7
    - source activate emergent
  script:
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  # - apt-get install libgl1-mesa-glx -y
  # - apt-get install libx11-xcb1 -y
  - python setup.py develop
  # - cd tutorials
  # - jupyter nbconvert --to notebook --execute "Getting started.ipynb"
  # - jupyter nbconvert --to notebook --execute "HTTP API.ipynb"
  - cd tests
  - python test_tutorials.py

# network_construction:
#   stage: network_construction
#   script:
#     - ls
#     - cd tutorials
#     - jupyter nbconvert --to python --execute "Getting started.ipynb"

# API_test:
#   script:
#     - cd emergent
#     - jupyter nbconvert --to notebook --execute "../tutorials/HTTP API.ipynb"
