image: continuumio/anaconda3:latest

stages:
  - build
  - network_construction

build:
  stage: build
  before_script:
    - conda create -n emergent python=3.7
    - source activate emergent
  script:
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - python setup.py develop

network_construction:
  stage: network_construction
  script:
    - cd tutorials
    - jupyter nbconvert --to python --execute "Getting started.ipynb"

# API_test:
#   script:
#     - cd emergent
#     - jupyter nbconvert --to notebook --execute "../tutorials/HTTP API.ipynb"
