image: continuumio/anaconda3:latest

stages:
  - build
  - network_construction

# before_script:
#   - conda create -n emergent python=3.7
#   - source activate emergent

build:
  stage: build
  script:
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - python setup.py develop

network_construction:
  stage: network_construction
  script:
    - cd emergent
    - ls
    - ls networks
    - python utilities/new.py test
    - ls networks
    - ls networks/test
    # - jupyter nbconvert --to notebook --execute "../tutorials/Getting started.ipynb"

# API_test:
#   script:
#     - cd emergent
#     - jupyter nbconvert --to notebook --execute "../tutorials/HTTP API.ipynb"
