image: continuumio/anaconda3:latest

before_script:
  - conda env create -n emergent python=3.7
  - source activate emergent

test:
  script:
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - python setup.py develop
