image: continuumio/anaconda3:latest

before_script:
  - conda create -n emergent python=3.7
  - source activate emergent

build:
  script:
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - python setup.py develop

network_construction:
  jupyter nbconvert --to notebook --execute "tutorials/Getting started.ipynb"

API_test:
  jupyter nbconvert --to notebook --execute "tutorials/HTTP API.ipynb"
